---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pftra478/public_html/
    - /bin/cp postToFile.mjs $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp -R data $DEPLOYPATH




# ---
# deployment:
#   tasks:
#     - export DEPLOYPATH=/home/$USER/public_html/
#     - rsync -avz --delete . $DEPLOYPATH
