# ---
# deployment:
#   tasks:
#     - export DEPLOYPATH=/home/pftra478/public_html/
#     - /bin/cp postToFile.mjs $DEPLOYPATH
#     - /bin/cp package.json $DEPLOYPATH
#     - /bin/cp -R data $DEPLOYPATH

# ---
# deployment:
#   tasks:
#     - export DEPLOYPATH=/home/pftra478/public_html/
    
#     # Navigate to the directory where your Git repository is located
#     - cd /home/pftra478/repositories/api-endpoints

#     # Pull the latest changes and LFS files
#     - git pull
#     - git lfs pull
    
#     # Sync the files to the deployment path
#     - rsync -avz --delete . $DEPLOYPATH



---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pftra478/public_html/
    - rsync -avz --delete . $DEPLOYPATH
